server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.99.183.154:31052/prd_esms?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: Fpi@123456
  data:
    mongodb:
      uri: mongodb://localhost:27017/testdb
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      acks: all                          #0 不保证数据一定发送成功,发送效率最高   1 保证leader成功并持久化,不保证follower是否写成功   all最强保证,效率最低
    consumer:
      group-id: group
  jpa:
    #    hibernate:
    #      ddl-auto: update
    show-sql: true
  redis:
    database: 0
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.alieducation.entity
  configuration:
    useGeneratedKeys: true
    mapUnderscoreToCamelCase: true


#mapper:
#  mappers: com.alieducation.util.TKMapper
#  not-empty: false
#  identity: MYSQL

##配置日志
#logging:
#  #此处存放日志的路径
#  path:
#    config: classpath:config/logback-spring.xml
#  #指定不同目录下的日志的级别
#  level:
#    com.shimain.springboot.mapper: DEBUG